#!/bin/sh

. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"

# this script is only for ABF chroots
[[ $CHROOT_NAME =~ ^abf ]] || return 0

[[ "$CHROOT_BTRFS_SOURCE_SUBVOLUME" ]] && {
	BTRFS_DIR=$(dirname $CHROOT_BTRFS_SOURCE_SUBVOLUME)
	BTRFS_SUB=$(basename $CHROOT_BTRFS_SOURCE_SUBVOLUME)
}
[[ -z $BTRFS_DIR ]] && {
	BTRFS_DIR=$(dirname $CHROOT_DIRECTORY)
	BTRFS_SUB=$(basename $CHROOT_DIRECTORY)
}

[[ -z $BTRFS_DIR || $BTRFS_DIR = '/' || $BTRFS_DIR = '' ]] && (
	echo Bad schroot config;
	exit 1
)

BTRFS_IMG=${BTRFS_DIR}.btrfs

[[ $STAGE = 'setup-start' ]] && {
	source /etc/abf/abf.conf || exit 1
	# FS setup
	mkdir -p /tmp/abf && chmod 0777 /tmp/abf
	
	# Initialize chroot image
	declare -A BASE_PKGS
	BASE_PKGS[abf32]="base base-devel sudo pacman yaourt xdelta3"
	BASE_PKGS[abf64]="${BASE_PKGS[abf32]} multilib-devel"

	[[ -d $BTRFS_DIR ]] || mkdir -p $BTRFS_DIR
	[[ -f $BTRFS_IMG ]] || (
		echo "${BTRFS_IMG} was not found. Creating new image..."
		dd if=/dev/zero of=$BTRFS_IMG bs=1M count=$CHROOT_IMG_SIZE
		mkfs.btrfs -L 'ABF_CHROOTS' $BTRFS_IMG
	)
	
	[[ -f $BTRFS_IMG ]] && [[ -d $BTRFS_DIR ]] && (
		# "Mounting BTRFS Image..."
		mount -o loop,compress=lzo $BTRFS_IMG $BTRFS_DIR || exit
		[[ ! -d $CHROOT_BTRFS_SNAPSHOT_DIRECTORY && ! -z $CHROOT_BTRFS_SNAPSHOT_DIRECTORY ]] && (
			mkdir -p $CHROOT_BTRFS_SNAPSHOT_DIRECTORY
		)
		[[ -d ${BTRFS_DIR}/${BTRFS_SUB} ]] || (
			btrfs subvolume create ${BTRFS_DIR}/${BTRFS_SUB}
			chmod 0755 ${BTRFS_DIR}/${BTRFS_SUB}
			echo "Making Arch Linux chroot filesystem..."
			if [[ $CHROOT_NAME == 'abf32' ]]; then
				setarch i386 /usr/sbin/mkarchroot -f -C /etc/abf/pacman-i686.conf ${BTRFS_DIR}/${BTRFS_SUB}/ ${BASE_PKGS[$CHROOT_NAME]}
			else
				/usr/sbin/mkarchroot -f -C /etc/abf/pacman-x86_64.conf ${BTRFS_DIR}/${BTRFS_SUB}/ ${BASE_PKGS[$CHROOT_NAME]}
			fi
		)
	)
} || true

[[ $STAGE = 'setup-stop' ]] && {
	# Unmounting BTRFS Image...
	mount | grep -qe "$BTRFS_DIR" && {
		sleep 3
		umount "$BTRFS_DIR"
	}
} || true
