#!/bin/sh

. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"

[[ "$CHROOT_BTRFS_SOURCE_SUBVOLUME" ]] && {
	BTRFS_DIR=$(dirname $CHROOT_BTRFS_SOURCE_SUBVOLUME)
	BTRFS_SUB=$(basename $CHROOT_BTRFS_SOURCE_SUBVOLUME)
}
[[ -z $BTRFS_DIR ]] && {
	BTRFS_DIR=$(dirname $CHROOT_DIRECTORY)
	BTRFS_SUB=$(basename $CHROOT_DIRECTORY)
}

[[ -z $BTRFS_DIR || $BTRFS_DIR = '/' || $BTRFS_DIR = '' ]] && (
	echo Bad schroot config;
	exit 1
)

BTRFS_IMG=${BTRFS_DIR}.btrfs

[[ $STAGE = 'setup-start' ]] && {
	declare -A BASE_PKGS
	BASE_PKGS[abf32]="base base-devel sudo pacman yaourt xdelta3"
	BASE_PKGS[abf64]="${BASE_PKGS[abf32]} multilib-devel"

	[[ -d $BTRFS_DIR ]] || mkdir -p $BTRFS_DIR
	[[ -f $BTRFS_IMG ]] || (
		# ${BTRFS_IMG} was not found. Creating...
		dd if=/dev/zero of=$BTRFS_IMG bs=1k count=2M
		mkfs.btrfs -L 'ABF_CHROOTS' $BTRFS_IMG
	)
	
	[[ -f $BTRFS_IMG ]] && [[ -d $BTRFS_DIR ]] && (
		# Mounting BTRFS Image...
		mount -o loop,compress=lzo $BTRFS_IMG $BTRFS_DIR
		[[ ! -d $CHROOT_BTRFS_SNAPSHOT_DIRECTORY && ! -z $CHROOT_BTRFS_SNAPSHOT_DIRECTORY ]] && (
			mkdir -p $CHROOT_BTRFS_SNAPSHOT_DIRECTORY
		)
		[[ -d ${BTRFS_DIR}/${BTRFS_SUB} ]] || (
			btrfs subvolume create ${BTRFS_DIR}/${BTRFS_SUB}
			chmod 0755 ${BTRFS_DIR}/${BTRFS_SUB}
			if [[ $CHROOT_NAME == 'abf32' ]]; then
				setarch i386 /usr/sbin/mkarchroot -f -C /etc/abf/pacman-i686.conf ${BTRFS_DIR}/${BTRFS_SUB}/ ${BASE_PKGS[$CHROOT_NAME]}
			else
				/usr/sbin/mkarchroot -f -C /etc/abf/pacman-x86_64.conf ${BTRFS_DIR}/${BTRFS_SUB}/ ${BASE_PKGS[$CHROOT_NAME]}
			fi
			mkarchroot -r /usr/sbin/locale-gen ${BTRFS_DIR}/${BTRFS_SUB}/
		)
	)
} || true

[[ $STAGE = 'setup-stop' ]] && {
	# Unmounting BTRFS Image...
	[[ -f "${BTRFS_IMG}" ]] && [[ -d "$BTRFS_DIR" ]] && (
		sleep 2 && umount "$BTRFS_DIR"
	)
} || true
