#!/bin/sh

. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"

# this script is only for ABF chroots
[[ $CHROOT_NAME =~ ^abf ]] || return 0

[[ $STAGE = 'setup-start' ]] && {
	mknod -m 666 "${CHROOT_PATH}/dev/null" c 1 3
	mknod -m 666 "${CHROOT_PATH}/dev/zero" c 1 5
	mknod -m 600 "${CHROOT_PATH}/dev/console" c 5 1
	mknod -m 644 "${CHROOT_PATH}/dev/random" c 1 8
	mknod -m 644 "${CHROOT_PATH}/dev/urandom" c 1 9
	mknod -m 666 "${CHROOT_PATH}/dev/tty" c 5 0
	mknod -m 666 "${CHROOT_PATH}/dev/tty0" c 4 0
	mknod -m 666 "${CHROOT_PATH}/dev/full" c 1 7
	ln -s /proc/kcore "${CHROOT_PATH}/dev/core"
	ln -s /proc/self/fd "${CHROOT_PATH}/dev/fd"
	ln -s /proc/self/fd/0 "${CHROOT_PATH}/dev/stdin"
	ln -s /proc/self/fd/1 "${CHROOT_PATH}/dev/stdout"
	ln -s /proc/self/fd/2 "${CHROOT_PATH}/dev/stderr"
} || true

#[[ $STAGE = 'setup-stop' ]] && {

#} || true
